FROM debian:bullseye-slim

LABEL MAINTAINER="patrick@kite4fun.nl"

RUN apt-get update && \
  apt-get install -y apt-utils libterm-readline-perl-perl &&  \
  apt-get install -y openjdk-17-jre curl git locales gradle && \
  apt-get clean

RUN git clone https://github.com/AsamK/signal-cli.git
WORKDIR /signal-cli
RUN ./gradlew build && \
  ./gradlew installDist && \
 ln -s /signal-cli/build/install/signal-cli signal

USER nobody
VOLUME /config
ENTRYPOINT ["/signal-cli/build/install/signal-cli/bin/signal-cli", "--config", "/config"]
